/* ===================================================
   GATI NODE TRANSPORT — INTERACTIONS & ANIMATIONS
   =================================================== */

document.addEventListener('DOMContentLoaded', () => {
  'use strict';

  /* ---- Signal to CSS that JS is ready ---- */
  document.body.classList.add('js-loaded');

  /* ---- DOM Refs ---- */
  const navbar    = document.getElementById('navbar');
  const hamburger = document.getElementById('hamburger');
  const mobileNav = document.getElementById('mobileNav');
  const backToTop = document.getElementById('backToTop');
  const navLinks  = document.querySelectorAll('.nav-links a, .mobile-nav a:not(.btn)');
  const toast     = document.getElementById('toast');

  /* ================================================
     1. HERO FLOATING PARTICLES (generated by JS)
     ================================================ */
  const particleContainer = document.getElementById('heroParticles');
  if (particleContainer) {
    const count = 18;
    for (let i = 0; i < count; i++) {
      const p = document.createElement('div');
      p.className = 'particle';
      const size = Math.random() * 4 + 2;          // 2–6px
      const left = Math.random() * 100;             // 0–100%
      const bottom = Math.random() * 40;            // 0–40%
      const duration = Math.random() * 8 + 6;      // 6–14s
      const delay = Math.random() * 8;             // 0–8s
      const opacity = Math.random() * 0.4 + 0.2;  // 0.2–0.6
      p.style.cssText = `
        width:${size}px; height:${size}px;
        left:${left}%; bottom:${bottom}%;
        opacity:${opacity};
        animation-duration:${duration}s;
        animation-delay:-${delay}s;
      `;
      particleContainer.appendChild(p);
    }
  }

  /* ================================================
     2. NAVBAR — scroll + active link
     ================================================ */
  const sections = document.querySelectorAll('section[id]');

  function onScroll() {
    const scrollY = window.scrollY;
    if (navbar) navbar.classList.toggle('scrolled', scrollY > 60);
    if (backToTop) backToTop.classList.toggle('visible', scrollY > 600);

    let current = '';
    sections.forEach(sec => {
      if (scrollY >= sec.offsetTop - 120) current = sec.getAttribute('id');
    });
    navLinks.forEach(link => {
      const href = link.getAttribute('href');
      if (href) link.classList.toggle('active', href === '#' + current);
    });
  }

  window.addEventListener('scroll', onScroll, { passive: true });
  onScroll();

  if (backToTop) {
    backToTop.addEventListener('click', () => window.scrollTo({ top: 0, behavior: 'smooth' }));
  }

  /* ================================================
     3. MOBILE NAV
     ================================================ */
  if (hamburger && mobileNav) {
    hamburger.addEventListener('click', () => {
      hamburger.classList.toggle('active');
      mobileNav.classList.toggle('open');
      document.body.style.overflow = mobileNav.classList.contains('open') ? 'hidden' : '';
    });
    mobileNav.querySelectorAll('a').forEach(a => {
      a.addEventListener('click', () => {
        hamburger.classList.remove('active');
        mobileNav.classList.remove('open');
        document.body.style.overflow = '';
      });
    });
  }

  /* ================================================
     4. SCROLL ANIMATIONS (Intersection Observer)
     ================================================ */
  const animEls = document.querySelectorAll('.fade-up, .fade-left, .fade-right');

  if ('IntersectionObserver' in window && animEls.length > 0) {
    const observer = new IntersectionObserver((entries) => {
      entries.forEach(entry => {
        if (entry.isIntersecting) {
          entry.target.classList.add('visible');
          observer.unobserve(entry.target);
        }
      });
    }, { threshold: 0.08, rootMargin: '0px 0px -20px 0px' });

    animEls.forEach(el => observer.observe(el));
  } else {
    animEls.forEach(el => el.classList.add('visible'));
  }

  /* ================================================
     5. STATS — Count-Up Animation
     ================================================ */
  const statNumbers = document.querySelectorAll('.stat-number[data-target]');
  let statsCounted = false;

  function countUp(el) {
    const target = parseInt(el.dataset.target, 10);
    const steps = 60;
    const duration = 2000;
    let step = 0;
    const timer = setInterval(() => {
      step++;
      const current = Math.min(Math.round((target / steps) * step), target);
      el.textContent = current + '+';
      if (step >= steps) { clearInterval(timer); el.textContent = target + '+'; }
    }, duration / steps);
  }

  if ('IntersectionObserver' in window && statNumbers.length > 0) {
    const statsObs = new IntersectionObserver((entries) => {
      entries.forEach(entry => {
        if (entry.isIntersecting && !statsCounted) {
          statsCounted = true;
          statNumbers.forEach(el => countUp(el));
          statsObs.disconnect();
        }
      });
    }, { threshold: 0.2 });
    const statsSection = document.getElementById('stats');
    if (statsSection) statsObs.observe(statsSection);
  }

  /* ================================================
     6. STAR RATING
     ================================================ */
  const starContainer = document.getElementById('starRating');
  const ratingInput   = document.getElementById('ratingValue');

  if (starContainer && ratingInput) {
    const stars = starContainer.querySelectorAll('.star');

    function setStars(value, cls) {
      stars.forEach((s, i) => s.classList.toggle(cls, i < value));
    }

    stars.forEach(star => {
      star.addEventListener('mouseenter', () => setStars(+star.dataset.value, 'hover'));
      star.addEventListener('click', () => {
        const val = +star.dataset.value;
        ratingInput.value = val;
        setStars(val, 'active');
      });
    });
    starContainer.addEventListener('mouseleave', () => stars.forEach(s => s.classList.remove('hover')));
  }

  /* ================================================
     7. TOAST
     ================================================ */
  function showToast(msg, dur) {
    if (!toast) return;
    toast.textContent = msg;
    toast.classList.add('show');
    setTimeout(() => toast.classList.remove('show'), dur || 3000);
  }

  /* ================================================
     8. FORM SUBMISSIONS
     ================================================ */
  const reviewForm = document.getElementById('reviewForm');
  if (reviewForm) {
    reviewForm.addEventListener('submit', e => {
      e.preventDefault();
      if (ratingInput && ratingInput.value === '0') { showToast('⭐ Please select a star rating'); return; }
      showToast('✅ Thank you! Your review has been submitted for verification.');
      reviewForm.reset();
      if (ratingInput) ratingInput.value = '0';
      if (starContainer) starContainer.querySelectorAll('.star').forEach(s => s.classList.remove('active'));
    });
  }

  const contactForm = document.getElementById('contactForm');
  if (contactForm) {
    contactForm.addEventListener('submit', e => {
      e.preventDefault();
      showToast("✅ Message sent! We'll get back to you within 2 hours.");
      contactForm.reset();
    });
  }

  /* ================================================
     9. SMOOTH ANCHOR SCROLLING
     ================================================ */
  document.querySelectorAll('a[href^="#"]').forEach(anchor => {
    anchor.addEventListener('click', e => {
      const href = anchor.getAttribute('href');
      if (href === '#') return;
      const target = document.querySelector(href);
      if (target) {
        e.preventDefault();
        const offset = navbar ? navbar.offsetHeight + 10 : 80;
        window.scrollTo({ top: target.offsetTop - offset, behavior: 'smooth' });
      }
    });
  });

  /* ================================================
     10. FLOATING MOUSE PARALLAX on Hero Orbs
     ================================================ */
  const heroSection = document.getElementById('home');
  const orbs = document.querySelectorAll('.orb');

  if (heroSection && orbs.length) {
    heroSection.addEventListener('mousemove', e => {
      const { left, top, width, height } = heroSection.getBoundingClientRect();
      const x = ((e.clientX - left) / width - 0.5) * 30;
      const y = ((e.clientY - top)  / height - 0.5) * 30;

      orbs.forEach((orb, i) => {
        const factor = (i + 1) * 0.5;
        orb.style.transform = `translate(${x * factor}px, ${y * factor}px)`;
      });
    });

    heroSection.addEventListener('mouseleave', () => {
      orbs.forEach(orb => { orb.style.transform = ''; });
    });
  }

});
